spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_demo
    username: postgres
    password: runna
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: redis            
    port: 6379             
    password: yourpassword  
    jedis:
      pool:
        max-active: 10      
        max-idle: 5         
        min-idle: 1         
        max-wait: 2000      	
   
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: password

